# Generated by Django 5.0 on 2025-04-06 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do record, ente 2 e 20 caracteres', max_length=20, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Nome Record')),
                ('tipo_marca', models.CharField(choices=[('100M', '100 metros'), ('200M', '400 metros'), ('1KM', '1 KM'), ('5KM', '5 KM'), ('15KM', '15 KM'), ('20KM', '20 KM'), ('Meia Maratona', 'Meia Maratona'), ('30KM', '30 KM'), ('Maratona', 'Maratona'), ('Longa Distancia', 'Longa Distancia'), ('Longa Duração', 'Longa Duração')], default='100M', help_text='A marca em distância atingida.', max_length=30, verbose_name='Tipo da marca')),
                ('tipo_esporte', models.CharField(choices=[('Corrida', 'Corrida'), ('Corrida de trilhas', 'Corrida de trilhas'), ('Caminhada', 'Caminhada'), ('Treino de alta intesidade', 'Treino de intesidade'), ('Treino de força', 'Treino de força'), ('Treino Aerópico', 'Treino Aerópico'), ('Natação', 'Natação')], default='Corrida', help_text='Tipo de esporte realizado', max_length=30, verbose_name='Tipo de esporte')),
                ('ritmo', models.TimeField(help_text='Ritmo realizado', verbose_name='Ritmo')),
                ('durqcao', models.TimeField(help_text='Duracaçao do record', verbose_name='Duração')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
