# Generated by Django 5.0 on 2025-04-06 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='nome',
            field=models.CharField(help_text='Nome do record, ente 2 e 20 caracteres', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome Record'),
        ),
    ]
