# Generated by Django 5.0 on 2025-04-27 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0002_alter_record_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pefil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Informe um e-mail válido, minimo 10 caracters e maximo 100', max_length=100, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Emal')),
                ('nome', models.CharField(help_text='Inserir nome completo do usuário', max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Nome')),
                ('cpf', models.CharField(help_text='Insira um cpf contendo 11 caracters', max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF')),
                ('senha', models.CharField(help_text='Insira uma senha, minimo 5 caracters e maximo 10 caracters.', max_length=10, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Senha')),
                ('data_nasc', models.DateField()),
                ('local', models.CharField(help_text='Insira o local onde mora, minimo 3 caracters e maximo 100', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Local')),
                ('pais', models.CharField(help_text='Insira o pais onde mora, minimo 3 caracters e maximo 100', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Pais')),
                ('genero', models.CharField(choices=[('Corrida', 'Corrida'), ('Homem', 'Homem'), ('Mulher', 'Mulher'), ('Não binário', 'Não binário'), ('Não informado', 'Não informado')], default='Mulher', help_text='Insira o seu genero', max_length=50, verbose_name='Genero')),
                ('peso', models.FloatField(help_text='Insira o seu peso', verbose_name='Insira o peso')),
                ('pagina_pessoal', models.URLField(blank=True, help_text='Informe o link da sua página pessoal', max_length=150, verbose_name='Pagina pessoa')),
                ('biografia', models.CharField(blank=True, help_text='Insira sua biografia', max_length=1000, null=True, verbose_name='Biografia')),
                ('premimun', models.BooleanField(default=True, verbose_name='Premium')),
                ('membro_desde', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
