# Generated by Django 5.0 on 2025-04-27 04:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0003_pefil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome do Clube, minimo 3 caracters, maximo 100', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome')),
                ('local', models.CharField(help_text='Insira o local onde mora, minimo 3 caracters e maximo 100', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Local')),
                ('pais', models.CharField(help_text='Insira o pais onde mora, minimo 3 caracters e maximo 100', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Pais')),
                ('tipo_esporte', models.CharField(choices=[('Corrida', 'Corrida'), ('Corrida de trilhas', 'Corrida de trilhas'), ('Caminhada', 'Caminhada'), ('Treino de alta intesidade', 'Treino de intesidade'), ('Treino de força', 'Treino de força'), ('Treino Aerópico', 'Treino Aerópico'), ('Natação', 'Natação')], default='Corrida', help_text='Tipo de esporte realizado', max_length=30, verbose_name='Tipo de esporte')),
                ('biografia', models.CharField(blank=True, help_text='Informe o a biografia do clube', max_length=500, null=True, verbose_name='Biografia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='record',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Records', to='strava.pefil'),
        ),
        migrations.AlterField(
            model_name='pefil',
            name='data_nasc',
            field=models.DateField(help_text='Digite a data de nascimento', verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='pefil',
            name='membro_desde',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data em que se tornou membro', verbose_name='Membro desde'),
        ),
        migrations.AddField(
            model_name='pefil',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Clube', to='strava.clube'),
        ),
    ]
