# Generated by Django 5.0 on 2025-04-27 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0004_clube_record_perfil_alter_pefil_data_nasc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pefil',
            name='email',
            field=models.EmailField(help_text='Informe um e-mail válido, minimo 10 caracters e maximo 100', max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Emal'),
        ),
    ]
