# Generated by Django 5.0 on 2025-04-27 19:51

import strava.validators.funcoes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0005_alter_pefil_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pefil',
            name='data_nasc',
            field=models.DateField(help_text='Digite a data de nascimento', validators=[strava.validators.funcoes.validar_idade_minima], verbose_name='Data de nascimento'),
        ),
    ]
