# Generated by Django 5.0 on 2025-04-27 20:21

import django.core.validators
import django.db.models.deletion
import strava.validators.funcoes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0006_alter_pefil_data_nasc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkSociaisClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(help_text='Digite uma url com minimo de 4 caracters e no maximo 100 caracters', max_length=100, validators=[django.core.validators.MinLengthValidator(4), strava.validators.funcoes.validar_inicial_url_website], verbose_name='Url do website')),
                ('instagram', models.URLField(help_text='Digite uma url do instagram com minimo de 4 caracters e no maximo 100 caracters', max_length=100, validators=[django.core.validators.MinLengthValidator(4), strava.validators.funcoes.validar_inicial_url_instagram], verbose_name='Url do instagram')),
                ('facebook', models.URLField(help_text='Digite uma url do facebook com minimo de 4 caracters e no maximo 100 caracters', max_length=100, validators=[django.core.validators.MinLengthValidator(4), strava.validators.funcoes.validar_inicial_url_facebook], verbose_name='Url do facebook')),
                ('other', models.URLField(blank=True, help_text='Digite uma url com minimo de 4 caracters e no maximo 100 caracters', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Outra url')),
                ('clube', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links_sociais', to='strava.clube')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
