# Generated by Django 5.0 on 2025-04-28 02:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0007_linksociaisclube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do equipamento, minimo 5 caracters, maximo 50', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome')),
                ('marca', models.CharField(help_text='Marca do equipamento, minimo 5 caracters, maximo 50', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Modelo do equipamento, minimo 5 caracters, maximo 50', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Modelo')),
                ('apelido', models.CharField(help_text='Apelido do equipamento, minimo 5 caracters, maximo 50', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Apelido')),
                ('tipo_equipamento', models.CharField(choices=[('Tenis', 'Tenis'), ('Bicicleta', 'Bicicleta'), ('Dispositivo inteligente', 'Dispositivo inteligente')], default='Bicicleta', help_text='Tipo equipamento', max_length=100, verbose_name='Tipo equipamento')),
                ('tipo_esporte', models.CharField(choices=[('Corrida', 'Corrida'), ('Corrida de trilhas', 'Corrida de trilhas'), ('Caminhada', 'Caminhada'), ('Treino de alta intesidade', 'Treino de intesidade'), ('Treino de força', 'Treino de força'), ('Treino Aerópico', 'Treino Aerópico'), ('Natação', 'Natação')], default='Treino Aerópico', help_text='Tipo esporte', max_length=100, verbose_name='Tipo esporte')),
                ('distancia_total', models.FloatField(help_text='Distancia total', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distancia total')),
                ('distancia_prevista', models.IntegerField(help_text='Distancia prevista', validators=[django.core.validators.MinValueValidator(400)], verbose_name='Distancia prevista')),
                ('peso', models.FloatField(help_text='Peso', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso')),
                ('notas', models.TextField(help_text='Notas', verbose_name='Notas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome da atividade, minimo 5 caracters, maximo 40', max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('observacao', models.CharField(blank=True, help_text='Insira a observação da atividade, minimo 5 caracters, maximo 40', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('data', models.DateField(help_text='A data da atividade', verbose_name='Data')),
                ('tipo_esporte', models.CharField(choices=[('Corrida', 'Corrida'), ('Corrida de trilhas', 'Corrida de trilhas'), ('Caminhada', 'Caminhada'), ('Treino de alta intesidade', 'Treino de intesidade'), ('Treino de força', 'Treino de força'), ('Treino Aerópico', 'Treino Aerópico'), ('Natação', 'Natação')], default='Treino Aerópico', help_text='Tipo esporte', max_length=100, verbose_name='Tipo esporte')),
                ('inicio', models.TimeField(help_text='Inicio da atividade', verbose_name='Inicio da atividade')),
                ('duracao', models.TimeField(help_text='Duração da atividade', verbose_name='Duração da atividade')),
                ('distancia', models.FloatField(help_text='Distancia', verbose_name='Distancia')),
                ('ritmo', models.TimeField(help_text='Ritmo', verbose_name='Ritmo')),
                ('calorias', models.IntegerField(default=0, help_text='Calorias', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calorias')),
                ('elevacao_total', models.IntegerField(default=0, help_text='Elevação total', verbose_name='Elevação total')),
                ('equipamento', models.ManyToManyField(default=django.db.models.deletion.CASCADE, related_name='equipamento', to='strava.equipamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
