# Generated by Django 5.0 on 2025-04-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0008_equipamento_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='equipamento',
            field=models.ManyToManyField(related_name='equipamento', to='strava.equipamento'),
        ),
    ]
