# Generated by Django 5.0 on 2025-04-28 02:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0009_alter_atividade_equipamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do desafio, minimo 5 caracters, maximo 50', max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('desafio_ini', models.DateField(help_text='Data inicio', verbose_name='Data inicial')),
                ('desafio_fim', models.DateField(help_text='Data fim', verbose_name='Data fim')),
                ('tipo_esporte', models.CharField(choices=[('Corrida', 'Corrida'), ('Corrida de trilhas', 'Corrida de trilhas'), ('Caminhada', 'Caminhada'), ('Treino de alta intesidade', 'Treino de intesidade'), ('Treino de força', 'Treino de força'), ('Treino Aerópico', 'Treino Aerópico'), ('Natação', 'Natação')], default='Treino Aerópico', help_text='Tipo esporte', max_length=100, verbose_name='Tipo esporte')),
                ('visao_geral', models.TextField(blank=True, help_text='Visão geral', null=True, verbose_name='Visão geral')),
                ('selo', models.CharField(help_text='Selo', max_length=5, verbose_name='Selo')),
                ('atividade', models.ManyToManyField(help_text='Atividade', related_name='atividade', to='strava.atividade', verbose_name='Atividade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas', null=True, verbose_name='Notas'),
        ),
        migrations.CreateModel(
            name='DesafioAtividade',
            fields=[
                ('desafio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='strava.desafio')),
                ('meta_duracao', models.IntegerField(help_text='Tempo de atividades', verbose_name='Tempo de atividades')),
            ],
            options={
                'abstract': False,
            },
            bases=('strava.desafio',),
        ),
        migrations.CreateModel(
            name='DesafioAtividadeTempo',
            fields=[
                ('desafio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='strava.desafio')),
                ('meta_duracao', models.IntegerField(help_text='Tempo de atividades', verbose_name='Tempo de atividades')),
            ],
            options={
                'abstract': False,
            },
            bases=('strava.desafio',),
        ),
        migrations.CreateModel(
            name='DesafioTempo',
            fields=[
                ('desafio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='strava.desafio')),
                ('meta_duracao', models.TimeField(help_text='Tempo da meta', verbose_name='Tempo da meta')),
            ],
            options={
                'abstract': False,
            },
            bases=('strava.desafio',),
        ),
    ]
