# Generated by Django 5.0 on 2025-06-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0010_desafio_alter_equipamento_notas_desafioatividade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pefil',
            options={'permissions': [('generate_code_perfil', 'can generate new codes')]},
        ),
    ]
