# Generated by Django 5.0 on 2025-04-08 01:29

import aula_validadores.validators.cod
import aula_validadores.validators.funcoes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10), aula_validadores.validators.funcoes.validate_par, aula_validadores.validators.cod.CodValidator('4444444444')])),
                ('nome', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
